version: '3'

services:
  nest_api_app:
    container_name: nest_api
    build: .
    environment:
      - DB_HOST=nest_api_postgres
      - DB_PORT=5432
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - DB_NAME=nest_api
      - APP_SECRET=208b176ff7baf82b932ea6eb5f9afad1
    volumes:
      - .:/home/api
    command: yarn start:dev
    ports:
      - 5000:5000

  nest_api_postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_DB=nest_db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - TZ=GMT
    ports:
      - 5432:5432
